### ISSUE TITLE
Braintree merchant information cannot be hardcoded

### ISSUE THREAD

**Issue by warpech** [handsoncode-apps/Braintree#10]
For practical and security reasons, merchant information cannot be hardcoded in:

https://github.com/handsoncode-apps/BraintreeDemoApp/blob/master/BrainTreeApi/Services/TransactionService/Transaction.cs
https://github.com/handsoncode-apps/BraintreeDemoApp/blob/master/BrainTreeApi/Services/CustomerService/Customer.cs

This information can lead to anyone with the access to this Git repo (which is public!) to make API calls to Briaintree.

The API key used there should be deleted in Braintree and a new one should be generated.

**Comment by jakubklekota** [comment]
Fixed

**Comment by warpech** [comment]
For anyone interested - what can happen when private credentials are pushed to GitHub: https://www.humankode.com/security/how-a-bug-in-visual-studio-2015-exposed-my-source-code-on-github-and-cost-me-6500-in-a-few-hours

**Comment by warpech** [comment]
This was not fixed completely, because you kept the old API key despite my request:

> The API key used there should be deleted in Braintree and a new one should be generated.

I have deleted the old API key now
